# Path to oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Detect OS
OS=`uname`

# Set name of the theme to load.
# agnoster theme requires special fonts. 
# See https://github.com/robbyrussell/oh-my-zsh/issues/1906
ZSH_THEME="agnoster"

# Mac specific settings
if [ "$OS" = 'Darwin' ]; then
    alias vi="mvim -v"
    plugins=(git brew osx python)

# FreeBSD specific settings
elif [ "$OS" = 'FreeBSD' ]; then
    alias vi="vim"
fi

# TODO Move exports to separate file
PATH="$HOME/bin:/usr/local/bin:$PATH"

# run Oh My zsh
source $ZSH/oh-my-zsh.sh

# Enable shell integration with iTerm2
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
