# Path to oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Detect OS
OS=`uname`

# Set name of the theme to load.
# agnoster theme requires special fonts. 
# See https://github.com/robbyrussell/oh-my-zsh/issues/1906
ZSH_THEME="agnoster"

# Mac specific settings
if [ "$OS" = 'Darwin' ]; then
    alias vi="mvim -v"
    plugins=(git brew osx svn python mvn)
    export JAVA_TOOLS_OPTIONS=-Djava.awt.headless=true
    export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
fi

# TODO Move exports to separate file
PATH="$HOME/bin:/usr/local/bin:$PATH:$HOME/anaconda/bin"

# run Oh My zsh
source $ZSH/oh-my-zsh.sh

# This was added by iTerm
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
