# Path to oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Detect OS
OS=`uname`

# Set name of the theme to load.
# agnoster theme requires special fonts. 
# See https://github.com/robbyrussell/oh-my-zsh/issues/1906
ZSH_THEME="agnoster"

# Mac specific settings
if [ "$OS" = 'Darwin' ]; then
    alias vi="mvim -v"
    plugins=(git brew osx svn python mvn)
    export JAVA_HOME=`/usr/libexec/java_home -v 1.8`

    # Prevent headless Java Apps from appearing on the Dock Bar
    export JAVA_TOOLS_OPTIONS=-Djava.awt.headless=true
# FreeBSD specific settings
elif [ "$OS" = 'FreeBSD' ]; then
    alias vi="vim"
    alias python=python2.7
    alias python3=python3.5
fi

# TODO Move exports to separate file
PATH="$HOME/bin:/usr/local/bin:$PATH:$HOME/Python/anaconda/bin"

# run Oh My zsh
source $ZSH/oh-my-zsh.sh

# Enable shell integration with iTerm2
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
